services:

  invoice-processor:

    image: invoice-processor:1.0

    build:
      context: .
      dockerfile: Dockerfile

    container_name: invoice-processor

    env_file:
      - .env

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      # Input invoices from host
      - ./invoices:/app/invoices:ro

      # Generated JSON/results on host
      - ./output:/app/output

      # Persistent PaddleOCR model cache
      - paddle-model-cache:/root/.paddlex
      # Source code for development
      - ./src:/app/src


volumes:
  paddle-model-cache: